src/objects/ITOP_Device_Type__c.object
<CustomObject>
    <description>type of device supported by IT On Point and Eli Lilly, including tablet, smart phone, wearable, etc.</description>
    <label>ITOP Device Type</label>
    <nameField>
        <label>ITOP_Device_Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ITOP Device Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ITOP_Location__c.object
<CustomObject>
    <description>IT On Point locations, including walk up break &amp; fix kiosks</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employees__c</fullName>
        <label>Number of Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isOpen__c</fullName>
        <label>isOpen</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>status</label>
        <type>Checkbox</type>
    </fields>
    <label>ITOP Location</label>
    <nameField>
        <label>ITOP Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ITOP Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ITOP_Request__c.object
<CustomObject>
    <description>IT On Point request details listed with ticket</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>describe the problem briefly</description>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Related_Device_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Device Type</label>
        <referenceTo>ITOP_Device_Type__c</referenceTo>
        <relationshipLabel>ITOP Requests</relationshipLabel>
        <relationshipName>ITOP_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Primary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Primary</label>
        <referenceTo>ITOP_Request_Primary_Option__c</referenceTo>
        <relationshipLabel>ITOP Requests</relationshipLabel>
        <relationshipName>ITOP_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Secondary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Secondary</label>
        <referenceTo>ITOP_Request_Secondary_Option__c</referenceTo>
        <relationshipLabel>ITOP Requests</relationshipLabel>
        <relationshipName>ITOP_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ITOP Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ITOP Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ITOP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ITOP_Request_Primary_Option__c.object
<CustomObject>
    <label>ITOP Request Primary Option</label>
    <nameField>
        <label>ITOP Request Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ITOP Request Primary Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ITOP_Request_Secondary_Option__c.object
<CustomObject>
    <label>ITOP Request Secondary Option</label>
    <nameField>
        <label>ITOP Request Secondary Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ITOP Request Secondary Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ITOP_Ticket__c.object
<CustomObject>
    <description>Ticket request for IT On Point locations.</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>ITOP_Location__c</referenceTo>
        <relationshipLabel>ITOP Tickets</relationshipLabel>
        <relationshipName>ITOP_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes for IT On Point employee use only</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ITOP_Request reference/relationship unique for each ticket</description>
        <label>Request</label>
        <referenceTo>ITOP_Request__c</referenceTo>
        <relationshipLabel>ITOP Tickets</relationshipLabel>
        <relationshipName>ITOP_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Ticket status.  Requested upon creation.  Changed only by ITOP employees unless cancelled.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isPriority__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriority</label>
        <type>Checkbox</type>
    </fields>
    <label>ITOP Ticket</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ITOP Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ITOP_Ticket_Manager_Controller.cls
public with sharing class ITOP_Ticket_Manager_Controller {
    
    
    @AuraEnabled
    public static List<ITOP_Ticket__c> fetchTicketsForLocation(String location){
        List<ITOP_Ticket__c> tickets = [SELECT Id, 
                                        Name, 
                                        Request__r.Related_Primary__r.Name, 
                                        Request__r.Related_Secondary__r.Name,
                                        Request__r.Related_Device_Type__r.Name,
                                        Request__r.Description__c, 
                                        CreatedBy.Name, Notes__c, 
                                        isPriority__c, Status__c 
                                        FROM ITOP_Ticket__c 
                                       	WHERE Status__c!='Closed'
                                       	AND Location__r.Name =:location
                                       ORDER BY isPriority__c DESC, Name ASC];
        
        return tickets;
    }
    
    
    @AuraEnabled
    public static List<ITOP_Location__c> fetchAllLocations(){
        List<ITOP_Location__c> locations = [SELECT Id, Name, Employees__c, isOpen__c, status__c 
                                           	FROM ITOP_Location__c];
        return locations;
    }
    
    @AuraEnabled
    public static ITOP_Location__c getLocation(String inputName){
        List<ITOP_Location__c> locations = [SELECT Id, Name, Employees__c, isOpen__c, status__c FROM ITOP_Location__c WHERE Name=:inputName];
        return locations[0];
    }
    
    @AuraEnabled
    public static ITOP_Location__c addEmployeeToLocation(Id inputLocation){
        ITOP_Location__c location = [SELECT Id, Name, Employees__c, isOpen__c, status__c FROM ITOP_Location__c WHERE Id=:inputLocation];
        
        Decimal count = location.Employees__c;
        if (count<5){
        	count += 1;
            location.Employees__c = count;
            update location;
        }
        return location;
    }
    @AuraEnabled
    public static ITOP_Location__c subtractEmployeeFromLocation(Id inputLocation){
        ITOP_Location__c location = [SELECT Id, Name, Employees__c, isOpen__c, status__c FROM ITOP_Location__c WHERE Id=:inputLocation];
        
        Decimal count = location.Employees__c;
        if (count>1){
        	count -= 1;
            location.Employees__c = count;
            update location;
        }
        return location;
    }
    @AuraEnabled
    public static ITOP_Location__c toggleOpenAtLocation(Id inputLocation){
        ITOP_Location__c location = [SELECT Id, Name, Employees__c, isOpen__c, status__c FROM ITOP_Location__c WHERE Id=:inputLocation];
        Boolean openStatus = !location.status__c;
        location.status__c = openStatus;
        update location;
        return location;
    }
    @AuraEnabled
    public static ITOP_Ticket__c updateTicketNotes(Id inputId, String inputNotes){
        ITOP_Ticket__c ticket = [SELECT Id, 
                                        Name, 
                                        Request__r.Related_Primary__r.Name, 
                                        Request__r.Related_Secondary__r.Name,
                                        Request__r.Related_Device_Type__r.Name,
                                        Request__r.Description__c, 
                                        CreatedBy.Name, Notes__c, 
                                        isPriority__c, Status__c 
                                        FROM ITOP_Ticket__c
                                		WHERE Id=:inputId];
        ticket.Notes__c = inputNotes;
        update ticket;
        return ticket;
    }
    @AuraEnabled
    public static ITOP_Ticket__c openCurrentTicket(Id inputId){
        ITOP_Ticket__c ticket = [SELECT Id, 
                                        Name, 
                                        Request__r.Related_Primary__r.Name, 
                                        Request__r.Related_Secondary__r.Name,
                                        Request__r.Related_Device_Type__r.Name,
                                        Request__r.Description__c, 
                                        CreatedBy.Name, Notes__c, 
                                        isPriority__c, Status__c 
                                        FROM ITOP_Ticket__c
                                		WHERE Id=:inputId];
        ticket.Status__c = 'Open';
        update ticket;
        return ticket;
    }
    @AuraEnabled
    public static ITOP_Ticket__c closeCurrentTicket(Id inputId){
        ITOP_Ticket__c ticket = [SELECT Id, 
                                        Name, 
                                        Request__r.Related_Primary__r.Name, 
                                        Request__r.Related_Secondary__r.Name,
                                        Request__r.Related_Device_Type__r.Name,
                                        Request__r.Description__c, 
                                        CreatedBy.Name, Notes__c, 
                                        isPriority__c, Status__c 
                                        FROM ITOP_Ticket__c
                                		WHERE Id=:inputId];
        ticket.Status__c = 'Closed';
        update ticket;
        return ticket;
    }
    
    @AuraEnabled
    public static void transferCurrentTicket(Id ticketId, String locationName){
        ITOP_Ticket__c ticket = [SELECT Id, 
                                        Name, 
                                        isPriority__c, Status__c 
                                        FROM ITOP_Ticket__c
                                		WHERE Id=:ticketId];
        ITOP_Location__c location = [SELECT Id, Name FROM ITOP_Location__c WHERE Name=:locationName];
        ticket.Location__c = location.Id;
        ticket.isPriority__c = true;
        update ticket;
    }
    
    
    @AuraEnabled
    public static List<ITOP_Location__c> fetchOtherLocations(ITOP_Location__c inputLocation){
        List<ITOP_Location__c> otherLocations = [SELECT Id, Name, Employees__c, isOpen__c, status__c 
                                           	FROM ITOP_Location__c
                                                WHERE Id!=:inputLocation.Id];
        return otherLocations;
    }
    
    
    
    
    
    
    
}